baseURL = 'https://draconis-25.github.io/'
languageCode = 'en-us'
title = 'Yusuf Yavuzyigit'

theme = 'risotto'
publishDir = 'docs'

author = "Yusuf Yavuzyigit"
copyright = "Â© 2021 Yusuf Yavuzyigit"
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]

[params.theme]
palette = "solarized-dark"
mode = "dark-mode"

# Sidebar: about/bio
[params.about]
title = "Yusuf Yavuzyigit"
description = "Creator of the ArchuraProject and everything inside it, </br> at least for now."
#logo = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 5 <https://fontawesome.com/> ('fas fa-' or 'fab-fa' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/Draconis-25"

[[params.socialLinks]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:yusufyavuzyigit25@gmail.com"

#[menu]
#
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
